[build]
base = ""
publish = "www"
command = "npm run build-test"

[dev]
command = "npm run start"
functionsPort = 1234
targetPort = 4200
port = 4242

[[redirects]]
from = "/__/auth/*"
to = "https://sweet-home-385514.firebaseapp.com/__/auth/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
